### ISSUE TITLE
Example of connecting to custom triplestore

### ISSUE THREAD

**Issue by nicholsn** [rhizomik/rhizomerAPI#17]
Interesting project! I spotted this service on the [d2s website](https://d2s.semanticscience.org/docs/deploy-additional-services#rhizomereye) and I'm curious to deploy a local version that connects to AWS Neptune. 

Any chance you have an example of how I might configure that?

**Comment by rogargon** [comment]
Thanks @nicholsn

Yes, I've been doing some tests with Amazon Neptune and a preliminary guide is available from: https://hackmd.io/@rogargon/HJuWj0w94

Please, let me know if it helps.

**Comment by nicholsn** [comment]
@rogargon this is great! Thanks for sharing. I'll let you know if I run into any snags but this will help me get started.
