### ISSUE TITLE
Unable to create new dataset

### ISSUE THREAD

**Issue by ThomasThelen** [rhizomik/rhizomerAPI#21]
I tried testing this with a sparql [endpoint](http://128.111.104.62:7200/repositories/KWG-V2) on a GraphDB instance. The graph has 4 billion triples and I haven't been able to sync it with Rhizomer. I ran across the following error in the logs, shown below. Any ideas? The UI error is `Error retrieving endpoint graphs...` and the error banner shows `Http failure response for http://localhost:8080/datasets/KWG/endpoints/1/server/graphs:0 Unknown Error`.

```
rhizomer-api    | 2022-02-11 17:42:58.707  INFO 9 --- [nio-8080-exec-9] o.s.w.bind.annotation.ExceptionHandler   : Handling generic Exception: HttpException: -1 Unexpected error making the query: GET http://128.111.104.62:7200/repositories/KWG-V2?timeout=30000000&query=PREFIX%20%20rdfs:%20%3Chttp://www.w3.org/2000/01/rdf-schema%23%3E%0A%0ASELECT%20%20?class%20?label%20%28COUNT%28DISTINCT%20?instance%29%20AS%20?n%29%0AWHERE%0A%20%20%7B%20?instance%20%20a%20%20?class%0A%20%20%20%20FILTER%20%28%20%21%20isBlank%28?class%29%20%29%0A%20%20%20%20OPTIONAL%0A%20%20%20%20%20%20%7B%20?class%20%20rdfs:label%20%20?label%0A%20%20%20%20%20%20%20%20FILTER%20langMatches%28lang%28?label%29%2C%20%22en%22%29%0A%20%20%20%20%20%20%7D%0A%20%20%20%20OPTIONAL%0A%20%20%20%20%20%20%7B%20?class%20%20rdfs:label%20%20?label%20%7D%0A%20%20%7D%0AGROUP%20BY%20?class%20?label%0A
```

**Comment by rogargon** [comment]
We have tested with different SPARQL engines but are not sure if we did with GraphDB. We will check it and report back

**Comment by ThomasThelen** [comment]
One key difference is how graphs are partitioned. In Virtuoso, there's a single graph and all the other graphs are named graphs within it. In GraphDB, you can have an n number of _repositories_ which are independent graphs (they're not named graphs within a larger graph).

**Comment by ThomasThelen** [comment]
Thank you so much for looking into it! I'm looking forward to getting my deployment up with this :)
I'll go ahead and check my repository settings and logs to see if I'm timing out-thanks again!
